# (array) All donators. These will show up as the people donating to the user at `/beg`
[[donators]]
    name = "Obama"  # (string) The name of the donator
    icon_url = "https://cdn.discordapp.com/attachments/861715293615947868/885264878238052372/llnb9gjtche41.png"  # (string) The URL of the donator's icon. Square size recommended.

    # Represents custom quotes for the donator.
    [donators.quotes]
        success = [  # (array) The success quotes for the donator.
            "uhh my fellow americans i have {} for you",  # (string) The quote. Will be formatted with the reward.
            "my fellow americans here is uhh your reward its {}\nyour mother left it behind when we had uhh sexual relationships",  # (string) The quote. Will be formatted with the reward.
        ]
        fail = [  # (array) The fail quotes for the donator.
            "uhh my fellow americans uhh your mom is gay",  # (string) The quote.
            "uhh my fellow americans i have uhh sexual relationships with your mother",  # (string) The quote.
            "uhh my fellow americans uhh let me be clear uhh i had sexual relationships with uhh your mother",  # (string) The quote.
            "uhh your mom is uhh gay",  # (string) The quote.
            "my fellow americans uhh shut the fuck up"  # (string) The quote.
        ]

# (array) All donators. These will show up as the people donating to the user at `/beg`
[[donators]]
    name = "Thanos"  # (string) The name of the donator
    icon_url = "https://media.discordapp.net/attachments/861715293615947868/892549138502254652/2Q.png"  # (string) The URL of the donator's icon. Square size recommended.

    # Represents custom quotes for the donator.
    [donators.quotes]
        success = [  # (array) The success quotes for the donator.
            "your reward is {}\nnow fuck off or I'll snap your balls away",  # (string) The quote. Will be formatted with the reward.
        ]
        fail = [  # (array) The fail quotes for the donator.
            "begone before i snap your pp into dust",  # (string) The quote.
            "i'll snap ur pp out of existence",  # (string) The quote.
            "nah. **\\*snaps\\***",  # (string) The quote.
        ]

# (array) All donators. These will show up as the people donating to the user at `/beg`
[[donators]]
    name = "Roblox Noob"  # (string) The name of the donator
    icon_url = "https://media.discordapp.net/attachments/861715293615947868/892551354655051836/SmugJubilantAnemonecrab-size_restricted.gif"  # (string) The URL of the donator's icon. Square size recommended.

    # Represents custom quotes for the donator.
    [donators.quotes]
        success = []  # (array) The success quotes for the donator.
        fail = []  # (array) The fail quotes for the donator.

# (array) All donators. These will show up as the people donating to the user at `/beg`
[[donators]]
    name = "Shrek"  # (string) The name of the donator
    icon_url = "https://media.discordapp.net/attachments/844989674883383326/892554166675857408/communityIcon_6abire8zs7q41.png"  # (string) The URL of the donator's icon. Square size recommended.

    # Represents custom quotes for the donator.
    [donators.quotes]
        success = []  # (array) The success quotes for the donator.
        fail = []  # (array) The fail quotes for the donator.

# (array) All donators. These will show up as the people donating to the user at `/beg`
[[donators]]
    name = "Donald John Trump"  # (string) The name of the donator
    icon_url = "https://cdn.discordapp.com/attachments/777245222580650074/893592446859112528/trump.jpg"  # (string) The URL of the donator's icon. Square size recommended.

    # Represents custom quotes for the donator.
    [donators.quotes]
        success = [  # (array) The success quotes for the donator.
            "you're on the right side of the wall, have some {}",  # (string) The quote. Will be formatted with the reward.
            "have {} and don't forget to vote for me",  # (string) The quote. Will be formatted with the reward.
            "as a reward for completing the capitol quest, enjoy {}",
            "i let one of my hitmen kill joe biden and he dropped {}. i don't need it so you can have it",
        ]
        fail = [  # (array) The fail quotes for the donator.
            "america is too great for you!",  # (string) The quote.
            "america first, something else second, you aren't even on the list",  # (string) The quote.
            "you're on the wrong side of the wall, so you'll get nada",  # (string) The quote.
            "my sexy daughter told me not to give you money",  # (string) The quote.
            "my iq is too high for that",  # (string) The quote.
            "your face isn't orange enough for that",
        ]

# (array) All donators. These will show up as the people donating to the user at `/beg`
[[donators]]
    name = "Dick Roberts"

    # Represents custom quotes for the donator.
    [donators.quotes]
        success = []
        fail = []

# (array) All donators. These will show up as the people donating to the user at `/beg`
[[donators]]
    name = "Daniel the Damned"

    # Represents custom quotes for the donator.
    [donators.quotes]
        success = []
        fail = []

# (array) All donators. These will show up as the people donating to the user at `/beg`
[[donators]]
    name = "Bob"

    # Represents custom quotes for the donator.
    [donators.quotes]
        success = []
        fail = []

# (array) All donators. These will show up as the people donating to the user at `/beg`
[[donators]]
    name = "Walter"

    # Represents custom quotes for the donator.
    [donators.quotes]
        success = []
        fail = []

# (array) All donators. These will show up as the people donating to the user at `/beg`
[[donators]]
    name = "Napoleon Bonaparte"

    # Represents custom quotes for the donator.
    [donators.quotes]
        success = []
        fail = []

# (array) All donators. These will show up as the people donating to the user at `/beg`
[[donators]]
    name = "Bob Ross"

    # Represents custom quotes for the donator.
    [donators.quotes]
        success = []
        fail = []

# (array) All donators. These will show up as the people donating to the user at `/beg`
[[donators]]
    name = "Don Vito"

    # Represents custom quotes for the donator.
    [donators.quotes]
        success = []
        fail = []

# (array) All donators. These will show up as the people donating to the user at `/beg`
[[donators]]
    name = "Bill Cosby"

    # Represents custom quotes for the donator.
    [donators.quotes]
        success = []
        fail = []

# (array) All donators. These will show up as the people donating to the user at `/beg`
[[donators]]
    name = "Your Step-sis"

    # Represents custom quotes for the donator.
    [donators.quotes]
        success = []
        fail = []

# (array) All donators. These will show up as the people donating to the user at `/beg`
[[donators]]
    name = "Pp God"

    # Represents custom quotes for the donator.
    [donators.quotes]
        success = []
        fail = []

# (array) All donators. These will show up as the people donating to the user at `/beg`
[[donators]]
    name = "Random Guy"

    # Represents custom quotes for the donator.
    [donators.quotes]
        success = []
        fail = []

# (array) All donators. These will show up as the people donating to the user at `/beg`
[[donators]]
    name = "Genie"

    # Represents custom quotes for the donator.
    [donators.quotes]
        success = []
        fail = []

# (array) All donators. These will show up as the people donating to the user at `/beg`
[[donators]]
    name = "The guy you accidentally made eye contact with at the urinal"

    # Represents custom quotes for the donator.
    [donators.quotes]
        success = []
        fail = []

# (array) All donators. These will show up as the people donating to the user at `/beg`
[[donators]]
    name = "Your Mom"

    # Represents custom quotes for the donator.
    [donators.quotes]
        success = []
        fail = []

# (array) All donators. These will show up as the people donating to the user at `/beg`
[[donators]]
    name = "Your Daughter"

    # Represents custom quotes for the donator.
    [donators.quotes]
        success = []
        fail = []

# (array) All donators. These will show up as the people donating to the user at `/beg`
[[donators]]
    name = "Big Man Tyrone"

    # Represents custom quotes for the donator.
    [donators.quotes]
        success = []
        fail = []

# (array) All donators. These will show up as the people donating to the user at `/beg`
[[donators]]
    name = "Schl√∂pp"

    # Represents custom quotes for the donator.
    [donators.quotes]
        success = []
        fail = []
